### ISSUE TITLE
Update Docker run documentation

### ISSUE THREAD

**Issue by jjkirby** [anilallewar/microservices-basics-spring-boot#4]
You need to update documentation to reflect your image name and version on some of your docker run examples.  

docker run -d --name config-server -p 8888:8888 anilallewar/config-server

Should be

docker run -d --name config-server -p 8888:8888 anilallewar/basic-config-server:0.0.1

Dockercompoise appears OK

**Comment by anilallewar** [comment]
Updated, thanks :)
