### ISSUE TITLE
Ports exposed by rancher are not reachable

### ISSUE THREAD

**Issue by AbdelkaderR** [anilallewar/microservices-basics-spring-boot#6]
When i run project with Rancher, ports exposed by Rancher are not reachable.
If you look at the picture you can see ports exposed but when i try to access it this failed.
Thanks 
<img width="878" alt="rancher_dashboard" src="https://user-images.githubusercontent.com/28364926/32983009-3f601a20-cc8e-11e7-9577-53e9ee08398e.png">

**Comment by anilallewar** [comment]
Can you show the container listing to see if the host ports are mapped?

**Comment by anilallewar** [comment]
Closing non-active issue
